### PR TITLE
Allow hooking events to puppeteer page object

### PR DESCRIPTION
**Pull request by rochoa**
By default it hooks error events to console.error for better debugging.

### CODE REVIEW

**Review by IagoLast — APPROVED** [review]
💔

**Comment by IagoLast** [comment]
Maybe we should document this in the README ;)

**Comment by rochoa** [comment]
I was working on the README improvements. :\

**Comment by rochoa** [comment]
https://github.com/IagoLast/Exquisite/pull/8 😄

**Pull request merged**
